name: Deploy image
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]
  repository_dispatch:
  push:
    branches:
      - master
      - develop
      - '[vt][0-9].[0-9]+.[0-9x]+*'
    tags:
      - "*"
env:
  DHUBU: ${{secrets.DHUBU}}
  DHUBP: ${{secrets.DHUBP}}
  PROXY_ENDPOINT: "https://api.github.com/repos/neonlabsorg/neon-proxy.py"
  NEON_TESTS_ENDPOINT: ${{vars.NEON_TESTS_ENDPOINT}}
  DOCKERHUB_ORG_NAME: ${{vars.DOCKERHUB_ORG_NAME}}
  RUN_LINK_REPO: "neonlabsorg/neon-proxy.py"
  BUILD_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-image:
    runs-on: neon-evm-1
    outputs:
      evm_tag: ${{ steps.tags.outputs.evm_tag }}
      evm_sha_tag: ${{ steps.tags.outputs.evm_sha_tag }}
      evm_pr_version_branch: ${{ steps.tags.outputs.evm_pr_version_branch }}
      is_evm_release: ${{ steps.tags.outputs.is_evm_release }}
      neon_test_tag: ${{ steps.tags.outputs.neon_test_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Specify image tags
        run: |
          python3 ./.github/workflows/deploy.py specify_image_tags \
          --git_ref=${{ github.ref }} \
          --git_head_ref=${{ github.head_ref }} \
          --git_base_ref=${{ github.base_ref }}
      - name: Set outputs
        id: tags
        run: |
          echo "evm_tag=${{ env.EVM_TAG }}" >> "$GITHUB_OUTPUT"
          echo "evm_sha_tag=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          echo "evm_pr_version_branch=${{ env.PROXY_PR_VERSION_BRANCH }}" >> "$GITHUB_OUTPUT"
          echo "is_evm_release=${{ env.IS_EVM_RELEASE }}" >> "$GITHUB_OUTPUT"
          echo "neon_test_tag=${{ env.NEON_TEST_TAG }}" >> "$GITHUB_OUTPUT"
      - name: build docker image
        run: |
          python3 ./.github/workflows/deploy.py build_docker_image \
          --evm_sha_tag=${{ steps.tags.outputs.evm_sha_tag }}
      - name: publish image
        run: |
          python3 ./.github/workflows/deploy.py publish_image \
          --evm_sha_tag=${{ steps.tags.outputs.evm_sha_tag }} \
          --evm_tag=${{ steps.tags.outputs.evm_tag }}
  run-evm-tests:
    runs-on: test-runner
    needs:
      - build-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run tests
        run: |
          python3 ./.github/workflows/deploy.py run_tests \
          --evm_sha_tag=${{ needs.build-image.outputs.evm_sha_tag }} \
          --neon_test_tag=${{ needs.build-image.outputs.neon_test_tag }} \
          --run_number=${{ github.run_number }} \
          --run_attempt=${{ github.run_attempt }}
      - name: Cancel the build if job failed
        if: "failure()"
        uses: "andymckay/cancel-action@0.4"
  trigger-proxy-tests:
    runs-on: trigger-runner
    needs:
      - build-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Trigger proxy build
        run: |
          python3 ./.github/workflows/deploy.py trigger_proxy_action \
          --evm_pr_version_branch=${{ needs.build-image.outputs.evm_pr_version_branch }} \
          --is_evm_release=${{ needs.build-image.outputs.is_evm_release }} \
          --evm_sha_tag=${{ needs.build-image.outputs.evm_sha_tag }} \
          --evm_tag=${{ needs.build-image.outputs.evm_tag }} \
          --token=${{secrets.GHTOKEN }} \
          --labels='${{ toJson(github.event.pull_request.labels.*.name) }}' \
          --pr_url="${{ github.api_url }}/repos/${{ github.repository }}/issues" \
          --pr_number="${{ github.event.pull_request.number }}"
      - name: Cancel the build if job failed
        if: "failure()"
        uses: "andymckay/cancel-action@0.4"
  finalize-image:
    runs-on: neon-evm-1
    needs:
      - build-image
      - trigger-proxy-tests
      - run-evm-tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Finalize image
        run: |
          python3 ./.github/workflows/deploy.py finalize_image \
          --evm_sha_tag=${{ needs.build-image.outputs.evm_sha_tag }} \
          --evm_tag=${{ needs.build-image.outputs.evm_tag }}

      - name: Send notification to slack
        if: failure()
        run: |
          python3 ./.github/workflows/deploy.py send_notification \
          --evm_tag=${{ needs.build-image.outputs.evm_tag }} \
          --url=${{secrets.SLACK_EVM_CHANNEL_URL}} \
          --build_url=${BUILD_URL}
